language: python
python:
  - "3.5"
install:
  - chmod +x setup.sh
  - ./setup.sh
script:
  - chmod +x test.sh
  - ./test.sh
before_deploy:
  - ls -l
  - chmod +x deploy.sh
  - ./deploy.sh
deploy:
  provider: script
  script:
    - chmod +x deploy.sh
    - ./deploy.sh
  skip_cleanup: true
notifications:
  email: never
