language: python
python:
  - "3.5"
install:
  - chmod +x setup.sh
  - ./setup.sh
script:
  - chmod +x test.sh
  - ./test.sh
before_deploy:
  - chmod +x deploy.sh
  - ./deploy.sh
deploy:
  provider: script
  script: echo "hi"
  skip_cleanup: true
notifications:
  email: never
